version: '3'

services:
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "samuelbohl/sbbbikereservationplanner-client"
    ports:
      - "80:3000"
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "samuelbohl/sbbbikereservationplanner-backend"
    expose:
      - "8000"
    ports:
      - "8000:8000"